connector.name=iceberg
iceberg.catalog.type=hive_metastore
hive.metastore.uri=thrift://hive-service.efs-dev.svc.cluster.local:9083
iceberg.file-format=PARQUET
fs.native-azure.enabled=true
azure.account.auth.type=ACCESS_KEY
azure.account.key.kafkapoc1.dfs.core.windows.net=IhMcOxJynuBKNYEatG4hLjTmQAZ09U6CCekgqYzYkKcbTiFR4fwhBFU6QpstiDGW4yxRWY3qVRmZ+AStrc52VA==
