apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "hive.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}

spec:
  storageClassName: {{ .Values.persistence.storageClass }}

  accessModes:
    - {{ .Values.persistence.accessMode }}

  resources:
    requests:
      storage: {{ .Values.persistence.storage }}
