apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: hive
  type: {{ .Values.service.type }}

  ports:
    - name: hiveserver2
      port: {{ .Values.service.hiveserver2.port }}
      targetPort: {{ .Values.service.hiveserver2.port }}
      nodePort: {{ .Values.service.hiveserver2.nodePort }}

    - name: metastore
      port: {{ .Values.service.metastore.port }}
      targetPort: {{ .Values.service.metastore.port }}
      nodePort: {{ .Values.service.metastore.nodePort }}
