apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kafka.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "kafka.fullname" . }}-svc
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "kafka.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka.fullname" . }}
    spec:
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      containers:
        - name: kafka
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 9092
          command: ["/opt/kafka/bin/kafka-server-start.sh", "/opt/kafka/config/kraft/server.properties"]
          volumeMounts:
            - name: kafka-data
              mountPath: /tmp/kraft-combined-logs
  volumeClaimTemplates:
    - metadata:
        name: kafka-data
      spec:
        accessModes: [ "{{ .Values.persistence.accessMode }}" ]
        storageClassName: "{{ .Values.persistence.storageClass }}"
        resources:
          requests:
            storage: "{{ .Values.persistence.size }}"
