apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: kafka-pv
    volumeAttributes:
      containerName: {{ .Values.pv.containerName }}
      protocol: fuse2
      allowOther: "true"
    nodeStageSecretRef:
      name: {{ .Values.blobSecret.name }}
      namespace: {{ .Release.Namespace }}
