{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Release.Name }}-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Release.Name }}-pv
    volumeAttributes:
      containerName: tools
      protocol: fuse2
      allowOther: "true"
    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: {{ .Release.Namespace }}
{{- end }}
