apiVersion: v1
kind: Service
metadata:
  name: kafka-service-nodeport
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kafka
  type: {{ .Values.service.nodePort.type }}
  ports:
    - name: kafka
      protocol: TCP
      port: {{ .Values.service.nodePort.port }}
      targetPort: {{ .Values.service.nodePort.targetPort }}
      nodePort: {{ .Values.service.nodePort.nodePort }}
