apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-pvc
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ .Values.pvc.storageClass }}
  resources:
    requests:
      storage: {{ .Values.pvc.storage }}
