apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: {{ .Release.Namespace }}
data:
  redis.conf: |
    protected-mode no
    bind 0.0.0.0
    port {{ .Values.redis.port }}
    appendonly yes
    user admin on >admin ~* +@all
