apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "debezium.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: debezium
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: debezium
  template:
    metadata:
      labels:
        app: debezium
    spec:
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      containers:
        - name: debezium
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          command: ["/opt/kafka/bin/connect-distributed.sh", "/opt/kafka/config/connect-distributed.properties"]
          volumeMounts:
            - name: debezium-vol
              mountPath: {{ .Values.persistence.mountPath }}
              subPath: {{ .Values.persistence.subPath }}
      volumes:
        - name: debezium-vol
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.volumeName }}
