apiVersion: apps/v1
kind: Deployment
metadata:
  name: apicurio
  namespace: {{ .Release.Namespace }}
  labels:
    app: apicurio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: apicurio
  template:
    metadata:
      labels:
        app: apicurio
    spec:
      containers:
      - name: apicurio
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        ports:
        - containerPort: {{ .Values.service.port }}

        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "{{ .Values.kafka.bootstrapServers }}"

        volumeMounts:
        - name: apicurio-storage
          mountPath: /registry-data

      volumes:
      - name: apicurio-storage
        persistentVolumeClaim:
          claimName: apicurio-pvc
