apiVersion: v1
kind: PersistentVolume
metadata:
  name: apicurio-pv
spec:
  capacity:
    storage: {{ .Values.storage.size }}
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClass }}

  csi:
    driver: blob.csi.azure.com
    readOnly: false
    volumeHandle: {{ .Values.storage.volumeHandle }}

    volumeAttributes:
      containerName: {{ .Values.storage.containerName }}
      protocol: fuse2
      allowOther: "true"

    nodeStageSecretRef:
      name: azure-blob-secret
      namespace: {{ .Release.Namespace }}
