apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-blob-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.storage.class }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.size }}
