apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.webserver.serviceType }}
  selector:
    component: webserver
  ports:
    - port: {{ .Values.webserver.port }}
      targetPort: {{ .Values.webserver.port }}
      nodePort: {{ .Values.webserver.nodePort }}
