apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "trino.fullname" . }}-catalogs
  namespace: {{ .Release.Namespace }}
data:
  postgres.properties: |
    connector.name=postgresql
    connection-url=jdbc:postgresql://postgres.efs-dev.svc.cluster.local:5432/airflow?createDatabaseIfNotExist=true
    connection-user=airflow
    connection-password=airflow
  iceberghive.properties: |
    connector.name=iceberg
    iceberg.catalog.type=hive_metastore
    hive.metastore.uri=thrift://hive-service:9083
    iceberg.file-format=PARQUET
    fs.native-azure.enabled=true
    azure.auth-type=ACCESS_KEY
    azure.access-key=tPp1dwE/aOi4zbriyvTB8oIeMXze0J0+JJ6+OofDHhTRd+4/QthHLmLlVUQBGTEtLbc11YJiREoI+ASte0IqDA==
  hive1.properties: |
    connector.name=hive
    hive.metastore.uri=thrift://hive-service:9083
    hive.storage-format=PARQUET
    fs.native-azure.enabled=true
    azure.auth-type=ACCESS_KEY
    azure.access-key=tPp1dwE/aOi4zbriyvTB8oIeMXze0J0+JJ6+OofDHhTRd+4/QthHLmLlVUQBGTEtLbc11YJiREoI+ASte0IqDA==
