apiVersion: apps/v1
kind: Deployment
metadata:
  name: trino-worker
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: trino
      role: worker
  template:
    metadata:
      labels:
        app: trino
        role: worker

    spec:
      imagePullSecrets:
        - name: acr-secret

      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
        - name: trino
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TRINO_ROLE
              value: "worker"
            - name: TRINO_COORDINATOR_HOST
              value: "trino-coordinator"
            - name: JAVA_TOOL_OPTIONS
              value: "{{ .Values.worker.additionalJVMConfig | join " " }}"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: catalogs
              mountPath: /etc/trino/catalog
          resources:
{{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: catalogs
          configMap:
            name: {{ include "trino.fullname" . }}-catalogs
