apiVersion: v1
kind: Service
metadata:
  name: trino-worker
  namespace: {{ .Release.Namespace }}
spec:
  type: NodePort
  selector:
    app: trino
    role: worker
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30082
