apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-data-pv
spec:
  capacity:
    storage: {{ .Values.persistence.size }}
  accessModes:
    - {{ .Values.persistence.accessMode }}
  persistentVolumeReclaimPolicy: Delete
  storageClassName: {{ .Values.persistence.storageClass }}
  volumeMode: Filesystem
  local:
    path: {{ .Values.persistence.path }}
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: app
              operator: In
              values:
                - airflow
