replicaCount: 1

image:
  repository: crfmphbidevneu001.azurecr.io/trino
  tag: test
  pullPolicy: Always

coordinator:
  enabled: true
  replicas: 1
  additionalJVMConfig:
    - "-Dtrino.metrics.set=all"
    - "-Dtrino.metrics.enabled=true"
    - "-Dtrino.metrics.statsd.enabled=true"
    - "-Dtrino.metrics.statsd.host=statsd.default.svc.cluster.local"
    - "-Dtrino.metrics.statsd.port=8125"
    - "-Dtrino.metrics.statsd.period=5s"
    - "-Dtrino.metrics.statsd.prefix=trino"
  configProperties:
    coordinator: "true"
    node-scheduler.include-coordinator: "true"
    http-server.http.port: "8080"
    discovery.uri: "http://trino-coordinator:8080"
    web-ui.enabled: "true"
    catalog.management: "dynamic"

worker:
  enabled: true
  replicas: 1
  additionalJVMConfig:
    - "-Dtrino.metrics.set=all"
    - "-Dtrino.metrics.enabled=true"
    - "-Dtrino.metrics.statsd.enabled=true"
    - "-Dtrino.metrics.statsd.host=statsd.default.svc.cluster.local"
    - "-Dtrino.metrics.statsd.port=8125"
    - "-Dtrino.metrics.statsd.period=5s"
    - "-Dtrino.metrics.statsd.prefix=trino"
  configProperties:
    http-server.http.port: "8080"
    discovery.uri: "http://trino-coordinator:8080"
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 70

resources:
  limits:
    cpu: 1000m
    memory: 2Gi
  requests:
    cpu: 500m
    memory: 1Gi
