replicaCount: 1

image:
  repository: apicurio/apicurio-registry-kafkasql
  tag: 2.6.12.Final
  pullPolicy: Always

service:
  type: NodePort
  port: 8080
  nodePort: 30091

kafka:
  bootstrapServers: kafka-service:9092

storage:
  size: 50Gi
  storageClass: azureblob-sc
  containerName: tools
  volumeHandle: apicurio-pv
