replicaCount: 1

image:
  repository: crfmphbidevneu001.azurecr.io/kafka
  tag: latest
  pullPolicy: Always

imagePullSecrets:
  - name: acr-secret

service:
  type: NodePort
  port: 9092
  nodePort: 32092

persistence:
  enabled: true
  storageClass: azureblob-sc
  accessMode: ReadWriteMany
  size: 50Gi
