replicaCount: 1

image:
  repository: crfmphbidevneu001.azurecr.io/kafka
  tag: latest
  pullPolicy: Always

imagePullSecret: acr-secret

service:
  clusterIP:
    type: ClusterIP
    port: 9092
    targetPort: 9092

  nodePort:
    type: NodePort
    port: 9092
    targetPort: 9092
    nodePort: 32092

storage:
  size: 50Gi

pv:
  containerName: tools

blobSecret:
  name: azure-blob-secret
